<?php

function plusoshare_block_info(){
  $blocks = array();
  
  $blocks['plusoshare'] = array(
    'info' => t('Pluso share buttons'),
    'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;
}


function plusoshare_block_view($delta = ''){
  $block = array();
  switch ($delta){
  case 'plusoshare':
    $block['subject'] = '<none>';
    $block['content'] = theme('plusoshare');
    break;
  }
  return $block;
}

function plusoshare_theme($existing, $type, $theme, $path){
  $themes = array();
  $themes['plusoshare'] = array('template' => 'plusoshare');
  return $themes;
}

function plusoshare_block_configure($delta = ''){
  $form = array();
  // настройки по умолчанию
  $default = variable_get('plusoshare_options','')->options;
  
  
  if ( $delta == 'plusoshare'){
    $form['settings'] = array(
      '#type' => 'fieldset',
      '#title' => t('Settings'),
      '#collapsed' => TRUE,
      '#collapsible' => TRUE,
    );
    
    $form['settings']['size'] = array(
      '#title' => t('Size'),
      '#type' => 'radios',
      '#options' => array('small' => t('Small') . ' (20x20px)', 'medium' => t('Medium')  . ' (30x30px)', 'big' => t('Big') . ' (40x40px)'),
      '#default_value' => $default->size,
    );
    
    $form['settings']['shape'] = array(
      '#title' => t('Shape'),
      '#type' => 'radios',
      '#options' => array('square' => t('Square'), 'round' =>t('Round')),
      '#default_value' => "$default->shape",
    );
    
    $form['settings']['multiline'] = array(
      '#title' => t('Multiline'),
      '#type' => 'radios',
      '#options' => array('line' => t('No'), 'multiline' =>t('Yes')),
      '#default_value' => $default->multiline,
    );
    
    $form['settings']['counter'] = array(
      '#title' => t('Counter'),
      '#type' => 'radios',
      '#options' => array('nocounter' => t('No'), 'counter' =>t('Yes')),
      '#default_value' => $default->counter,
    );
    
    $form['settings']['layout'] = array(
      '#title' => t('Layout'),
      '#type' => 'radios',
      '#options' => array('vertical' => t('Vertical'), 'horizontal' =>t('Horizontal')),
      '#default_value' => $default->layout,
    );
    
    $form['appearance'] = array(
      '#type' => 'fieldset',
      '#title' => t('Appearance'),
      '#collapsed' => TRUE,
      '#collapsible' => TRUE,
    );
    
    $form['appearance']['color'] = array(
      '#type' => 'textfield',
      '#title' => t('Background color'),
      '#default_value' => $default->color,
      '#description' =>  'Empty value = transparent color',
    );
    
    $form['settings']['domain'] = array(
      '#type' => 'textfield',
      '#title' => t('Domain'),
      '#default_value' => $default->domain,
      '#description' =>  '',
    );
    
    $pluso_theme = array(
      '01' => 'Theme 01',
      '02' => 'Theme 02',
      '03' => 'Theme 03',
      '04' => 'Theme 04',
      '05' => 'Theme 05',
      '06' => 'Theme 06',
      '07' => 'Theme 07',
      '08' => 'Theme 08',
    );
    
    $form['appearance']['theme'] = array(
      '#title' => t('Theme'),
      '#type' => 'radios',
      '#options' => $pluso_theme,
      '#default_value' => $default->theme,
    );
  }
 
  return $form;
}

function plusoshare_block_save($delta = '', $edit = array()){
  if ( $delta == 'plusoshare' ){
    $settings = variable_get('plusoshare_options','');
    $options = $settings->options;
    
    foreach ($options AS $key => $val){
      $options->$key = $edit[$key];
    }
    
    $settings->options = $options;
    variable_set('plusoshare_options', $settings);
  } 
}

function template_preprocess_plusoshare(&$vars) {
  $vars['plusoshare'] = pluso_generate();
  $vars['script'] = variable_get('plusoshare_options','')->script;
}

function pluso_generate(){
  $pluso = array();
  $obj = variable_get('plusoshare_options','');
  
  $obj->options->theme = 'theme=' . $obj->options->theme;
  
  $pluso['options'] = 'data-options="' . implode((array)$obj->options, ',') . '"';
  $pluso['services'] = 'data-services="' . implode($obj->services, ',') . '"';
  $pluso['background'] = 'data-background="' . $obj->options->color . '"';
  $pluso['url'] = 'data-url="' . $obj->options->domain . '/' . $_GET['q'] . '"';
  return implode($pluso, ' ');
}


function plusoshare_menu(){
  $items = array();
  
  $items['admin/config/karbunkul'] = array(
    'title' => 'Karbunkul',
    'description' => '',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/karbunkul/plusoshare'] = array(
    'title' => 'Pluso share',
    'description' => 'Pluso share settings and services',
    'access callback' => TRUE,
    'page callback' => 'page_pluso',
    
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['admin/config/karbunkul/plusoshare/default'] = array(
    'title' => t('Pluso share'),
    'access callback' => TRUE,
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  
  $items['admin/config/karbunkul/plusoshare/settings'] = array(
    'title' => 'Settings',
    'description' => '',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plusoshare_settings_form'),
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );
  
  
  return $items;
}

function plusoshare_settings_form($form){
  $obj = variable_get('plusoshare_options','');
  
  $form['script'] = array(
    '#type' => 'textarea',
    '#title' => 'Script',
    '#rows' => 10,
    '#default_value' => $obj->script
  );
  
  $form['services'] = array(
    '#type' => 'textarea',
    '#title' => 'Services',
    '#rows' => 10,
    '#default_value' => $obj->source
  );
  
  $form = system_settings_form($form);
  
  return $form;
}

function page_pluso(){
  $obj = variable_get('plusoshare_options','');
  
  $ptn = "/\[.*\]/m";
  $str = $obj->source;
  preg_match_all($ptn, $str, $matches);
  dsm($matches[0]);
  
  
  //dsm();
  
  $out = array(
    '#type' => 'markup',
    '#markup' => 'Services',
  );
  
  
  return $out;
}